In [ ]:
'komplex Zahlen'

a = 2 + 3j
b = 1 - 1j
print(a + b)          # Addition
print(a * b)          # Multiplikation
print(abs(a))         # Betrag
print(a.conjugate())  # Konjugation


(3+2j)
(5+1j)
3.605551275463989
(2-3j)


In [45]:
'Lineare Algebra (Vektoren, Matrizen, Skalarprodukt)'

import numpy as np

# Vektoren
v = np.array([1, 2])
w = np.array([3, 4])

# Skalarprodukt
print(np.vdot(v, w))

# Norm
print(np.linalg.norm(v))

# Matrizen
A = np.array([[1, 2], [3, 4]])
print(A.T)            # Transponierte
print(A.conj().T)     # Hermitesch Transponierte



11
2.23606797749979
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [46]:
"""Für alles rund um Qubits, Quantenzustände und Quantenoperationen empfiehlt 
das Buch explizit Qiskit. Damit lassen sich Zustände präparieren, Manipulationen 
und Messungen simulieren sowie Visualisierungen erzeugen."""

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector

qc = QuantumCircuit(1)
statevector = Statevector.from_label('1')
print(statevector)


Statevector([0.+0.j, 1.+0.j],
            dims=(2,))


In [47]:
"""S. 51, Übung 2.1 Zeigen Sie, dass Unterräume selbst wieder Vektorräume sind.
Ein Unterraum ist eine Teilmenge von Vektoren, die selbst wieder wie ein "kleiner Vektorraum" 
funktioniert. Das heißt: Wenn du zwei Vektoren aus dem Unterraum nimmst und sie addierst, 
bist du immer noch im Unterraum. Das Gleiche gilt, wenn du einen Vektor mit einer Zahl (Skalar)
multiplizierst."""

import numpy as np

# Beispiel: Unterraum W des R^2, alle Vektoren der Form (x, 0)
def ist_unterraum(v1, v2, skalar):
    add = v1 + v2
    skal = skalar * v1
    return add[1] == 0 and skal[1] == 0

v1 = np.array([1, 0])
v2 = np.array([2, 0])
skalar = 3

print(ist_unterraum(v1, v2, skalar))  # Ausgabe: True

v1 = np.array([1, 1])  # y-Komponente ist 1 (nicht im Unterraum)
v2 = np.array([2, 0])  # y-Komponente ist 0 (im Unterraum)
skalar = 3

print(ist_unterraum(v1, v2, skalar))  # Was passiert?

def ist_unterraum_y_achse(v1, v2, skalar):
    add = v1 + v2
    skal = skalar * v1
    return add[0] == 0 and skal[0] == 0  # Jetzt prüfen wir x = 0 statt y = 0

v1 = np.array([0, 1])  # Liegt auf der y-Achse
v2 = np.array([0, 2])  # Liegt auf der y-Achse
skalar = 3

print(ist_unterraum_y_achse(v1, v2, skalar))  # Ausgabe: True



def ist_unterraum_x_gleich_y(v1, v2, skalar):
    add = v1 + v2
    skal = skalar * v1
    return add[0] == add[1] and skal[0] == skal[1]  # Prüft x = y

v1 = np.array([1, 1])  # x = y ✔
v2 = np.array([2, 2])  # x = y ✔
skalar = 3

print(ist_unterraum_x_gleich_y(v1, v2, skalar))  # Ausgabe: True


"""v1 = 5  # Kein Vektor, sondern eine Zahl
v2 = np.array([2, 0])
skalar = 3

print(ist_unterraum(v1, v2, skalar))  # Fehler!"""

"""v1 = np.array([1, 0, 0])  # 3D-Vektor
v2 = np.array([2, 0])     # 2D-Vektor
skalar = 3

print(ist_unterraum(v1, v2, skalar))  # Fehler!"""


def ist_unterraum_allgemein(v1, v2, skalar, bedingung):
    add = v1 + v2
    skal = skalar * v1
    return bedingung(add) and bedingung(skal)

def bedingung_x_achse(v):
    return v[1] == 0

v1 = np.array([1, 0])
v2 = np.array([2, 0])
skalar = 3

print(ist_unterraum_allgemein(v1, v2, skalar, bedingung_x_achse))  # True

True
False
True
True
True


In [48]:
'S. 51, Übung 2.2: Skalarprodukt und Norm. Sei H ein Hilbertraum. Zeigen Sie, dass eine Norm auf H definiert wird. '

def skalarprodukt(u, v):
    return np.vdot(u, v)

def norm(v):
    return np.linalg.norm(v)

u = np.array([1+1j, 2])
v = np.array([2, 3+1j])

print("Skalarprodukt:", skalarprodukt(u, v))
print("Norm von u:", norm(u))


Skalarprodukt: (8+0j)
Norm von u: 2.449489742783178


In [51]:
'S. 51 Übung 2.4 Sei V ein Vektorraum und A ∈ L(V ). Zeigen Sie, dass die Eigenräume von A invariante Unterräume von V sind.'


# Matrix und Eigenvektor
A = np.array([[2, 0], [0, 3]])
eigvals, eigvecs = np.linalg.eig(A)

print("Eigenwerte:", eigvals)
print("Eigenvektoren:\n", eigvecs)

# Wir nehmen den ersten Eigenvektor und wenden A darauf an
v = eigvecs[:, 0]
result = A @ v
print("A angewendet auf Eigenvektor:", result)
print("Vergleich: Eigenwert mal Eigenvektor:", eigvals[0] * v)



Eigenwerte: [2. 3.]
Eigenvektoren:
 [[1. 0.]
 [0. 1.]]
A angewendet auf Eigenvektor: [2. 0.]
Vergleich: Eigenwert mal Eigenvektor: [2. 0.]


In [52]:
'S.51 Übung 2.3 Gegeben ist eine komplexe quadratische Matrix. Zeigen Sie, dass die hermitesch transponierte Matrix und der adjungierte Operator identisch sind.'

import numpy as np

# Beispielmatrix mit komplexen Einträgen
A = np.array([[1+2j, 2-1j], [3+0j, 4-2j]])

# Hermitesch Transponierte (conjugate transpose)
A_H = A.conj().T

# Adjungierte (in NumPy identisch)
A_star = np.conjugate(A).T

print("Matrix A:")
print(A)
print("\nHermitesch Transponierte A^H:")
print(A_H)
print("\nAdjungierte A^*:")
print(A_star)

# Überprüfung, ob beide Matrizen gleich sind
print("\nSind A^H und A^* gleich?", np.allclose(A_H, A_star))


Matrix A:
[[1.+2.j 2.-1.j]
 [3.+0.j 4.-2.j]]

Hermitesch Transponierte A^H:
[[1.-2.j 3.-0.j]
 [2.+1.j 4.+2.j]]

Adjungierte A^*:
[[1.-2.j 3.-0.j]
 [2.+1.j 4.+2.j]]

Sind A^H und A^* gleich? True
